# Generated by Django 2.2.2 on 2019-06-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_score', models.DecimalField(decimal_places=3, max_digits=8)),
                ('negative_score', models.DecimalField(decimal_places=3, max_digits=8)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date', models.DateField()),
            ],
        ),
    ]
