# Generated by Django 2.2.2 on 2019-06-26 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='negative_score',
            new_name='sentiment_score',
        ),
        migrations.RemoveField(
            model_name='score',
            name='positive_score',
        ),
    ]
