# Generated by Django 2.1.2 on 2019-06-27 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190626_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprice',
            name='company_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Company'),
        ),
    ]
